meta_product_name: "Thor Energy"
meta_title: "Thor Energy - Get Back in Charge"
meta_description: "Thor Energy provides an easily accessible, comfortable solution for
on-the-go smartphone charging. No power banks, no cables needed: no more requirements.
Get Back in Charge when and where you want to."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
